### PR TITLE
Automatically add tags from source repositories while adding a new osb-repository

### PR DESCRIPTION
**Pull request by sanjayankur31**
- adds keyword api call
- adds description api call (did not use this in the front end because the github description was not appropriate for repo summary)
- removes automatic addition of tags "under the hood"

### CODE REVIEW

**Comment by filippomc** [comment]
@sanjayankur31 can you please create a PR from a OSB2 branch?

**Comment by filippomc** [comment]
> @sanjayankur31 can you please create a PR from a OSB2 branch?

I see the repo is public, I might as well use it, just want to save some time and reduce possible causes of errors, but I can use your branches if you prefer!

**Comment by sanjayankur31** [comment]
I've also pushed the branch to the osbv2 repo now, so you can use that if you prefer. I can't seem to change that here in the PR, though. 

You can always use any of my branches once I've opened PRs---not really sure it makes a difference because I make it a point to sync with this one before I start working on a PR.

**Comment by sanjayankur31** [comment]
Here's the branch on this repo: https://github.com/OpenSourceBrain/OSBv2/tree/fix/issue-409

**Review by filippomc — APPROVED** [review]
LGTM

**Comment by sanjayankur31** [comment]
Yeh, feel free to use them. Sorry, ill use osbv2 branches in the future.

-- 
Thanks,

Ankur

(Sent from mobile device)

**Pull request merged**
