### PR TITLE
Feature/748 - Warn the user when a resource or file could be overwritten

### PR DESCRIPTION
**Pull request by D-GopalKrishna**
Closes - #748 
Task - Added a warning message.

image

### CODE REVIEW

**Comment by filippomc** [comment]
@pgleeson are you happy with the solution and the wording?

**Comment by pgleeson** [comment]
Does this PR check that the file to be added actually currently exists in the workspace, or just shows a general warning about adding files?

**Comment by filippomc** [comment]
Change text to: Please note that adding a file when a file with the same name already exists...

**Comment by D-GopalKrishna** [comment]
@filippomc 
Changed the text to:
"Please note that adding a file when a file with the same name already exists will overwrite the previous version of the file in the workspace."

**Pull request merged**
