### PR TITLE
Minor tweaks to jupyterlab dockerfile

### PR DESCRIPTION
**Pull request by sanjayankur31**
- adds brian2tools (needed by brian tutorial)
- uses shallow netpyne clone (can we not use `pip install git+https...` here also @pgleeson ?)

PS: not sure if this is the right base branch to open against, but should be easily rebased to development/master.

### CODE REVIEW

**Comment by pgleeson** [comment]
Changes look good to me, tested locally. pip install git+https... could be used, but there might be some advantage to having an easily accessible local copy of netpyne in the image for testing purposes. 

Should probably be opened against the development branch though.

**Comment by sanjayankur31** [comment]
OK, sounds good. Rebased against develop now.

**Review by filippomc — COMMENTED** [review]
Looks good. Is there a specific reason why the pr is on top of release/0.4.0 rather than the development branch? @sanjayankur31

**Comment by sanjayankur31** [comment]
Nah, not really. I just saw that the release branch was the most recently active one. I'll rebase this to development now

**Comment by sanjayankur31** [comment]
@filippomc : rebased onto develop, and opened against develop now.

**Review by filippomc — APPROVED** [review]

**Comment by filippomc** [comment]
@sanjayankur31 now that is merged into the develop branch the v2dev deployment is automatically updated

**Pull request merged**
